name: Run Scripts Scheduled

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run scripts scheduled
        run: |
          docker compose -f ../test-docker/docker-compose.yml up
      
