name: Build and Run Scripts

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and run scripts
        run: |
          docker compose -f ../test-docker/docker-compose.yml up          
      - name: Display logs
        run: |
          docker logs -f script1
          docker logs -f script2
          
          
