name: Build and Run Scripts

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and run scripts
        run: |
          docker-compose -f docker-compose.yml up -d script1
          docker-compose -f docker-compose.yml up -d script2
